package com.mbj.ssassamarket.util

object Constants {
    const val AUTO_LOGIN = "autoLogin"
    const val NICKNAME_PATTERN = "^[a-zA-Z0-9가-힣]{2,8}$"
    const val NICKNAME_REQUEST = "setting_nickname_request_nickname"
    const val NICKNAME_ERROR = "setting_nickname_error_nickname"
    const val NICKNAME_VALID = "setting_nickname_valid"
    const val NICKNAME_DUPLICATE = "setting_nickname_duplicate"
    const val SUCCESS = "success"
    const val PROGRESS_DIALOG = "progressDialog"
    const val CURRENT_DATE_PATTERN = "yyyy-MM-dd'T'HH:mm:ss"
    const val CATEGORY_REQUEST = "카테고리를 선택해주세요"
    const val SHARED_PREFERENCE_KEY = "SsaSsaMarket"
    const val KEY_HOME_PRODUCT = "key_home_product"
    const val PATTERN_COMMA_THOUSANDS = "#,###"
    const val TITLE = "title"
    const val PRICE = "price"
    const val CONTENT = "content"
    const val CHAT_ROOMS = "chatRooms"
    const val CHATS = "chats"
    const val LAST_MESSAGE = "lastMessage"
    const val CHAT_ROOM_ID = "chatRoomId"
    const val OTHER_USER_ID = "otherUserId"
    const val OTHER_USER_NAME = "otherUserName"
    const val OTHER_LOCATION = "otherLocation"
    const val USER = "user"
    const val USER_ID = "userId"
    const val USER_NAME = "userName"
    const val LAT_LNG = "latLng"
    const val LAST_SENT_TIME = "lastSentTime"
    const val KILOMETER_PATTERN= "%.1f"
}
